#!/usr/bin/bash

# use ninja if installed
build_tool=""
if [ -f "/usr/bin/ninja" ]; then
    build_tool="-G Ninja"
fi

# build
cmake -B build -DCMAKE_BUILD_TYPE=Release -DKokkos_ENABLE_OPENMP=ON $build_tool
cmake --build build

export OMP_NUM_THREADS=$(./getcpus)
export OMP_PROC_BIND=true
export OMP_PLACES=cores

# run
./build/src/top.matrix_product 2500 2500 2500